# Generated by Django 4.1.4 on 2023-01-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_image_remove_placeimage_path_placeimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='path',
        ),
    ]
